####################
# set up languages
language: c

####################
# install packages
before_install:
  - travis/install-deps.sh

####################
# build script
script:
  - export PATH=.:${PATH} && ./travis/autogen.sh && ./travis/configure.sh && make && make check && ./travis/distcheck.sh

####################
# branch configuration
branches:
  only:
  - MimirGProMIntegration

####################
# os environments
sudo: required
osx_image: xcode7.3

####################
# deploy
#after_success:
#  - ./travis/deploy.sh
####################
# build matrix
matrix:
  include:
  - { os: linux, dist: precise }
  - { os: linux, dist: trusty }
  - { os: osx }
  allow_failures:
    - os: osx
